// Uses an isolated browser and temporary database; does not modify the user's community.
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'/Users/hxb/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');const os=require('node:os');const {spawn}=require('node:child_process');
const root=path.resolve(__dirname,'..');const temp=fs.mkdtempSync(path.join(os.tmpdir(),'bigmax-browser-'));const qa=path.join(root,'qa');fs.mkdirSync(qa,{recursive:true});
const server=spawn('python3',[path.join(root,'server.py'),'--port','0','--database',path.join(temp,'community.sqlite3')],{stdio:['ignore','pipe','pipe']});
let browser;
const ready=new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Test server did not start')),10000);server.stdout.on('data',buf=>{const match=buf.toString().match(/http:\/\/127\.0\.0\.1:\d+/);if(match){clearTimeout(timer);resolve(match[0]);}});server.on('error',reject);});
(async()=>{
 const base=await ready;browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce',colorScheme:'light'});const page=await context.newPage();const errors=[];page.on('pageerror',err=>errors.push(err.message));
 const noOverflow=async()=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Page overflow');
 await page.goto(base+'/#directory');await page.locator('.resource-card').first().waitFor();assert.equal(await page.locator('.resource-card').count(),24);await noOverflow();assert.equal(await page.title(),'健康生活社区');assert.equal(await page.locator('.hero img').count(),0);assert.ok(!(await page.locator('body').innerText()).includes('大白'));assert.ok(Math.abs(await page.locator('.hero h1').evaluate(e=>{const r=e.getBoundingClientRect();return r.left+r.width/2-innerWidth/2;}))<2);await page.screenshot({path:path.join(qa,'home.png')});
 await page.locator('.sidebar [data-category="food"]').click();await page.locator('.advanced-filters summary').click();await page.locator('#license').selectOption('AGPL-3.0');await page.locator('#hosted').check();await page.locator('#active-only').check();assert.ok(await page.locator('.resource-card').count()>0);assert.deepEqual((await page.locator('.resource-card h3').allTextContents()).sort(),['Mealie','KitchenOwl','Norish','Cuicuit','Recipe Yak'].sort());
 await page.goto(base+'/#directory?category=food');await page.locator('.resource-card [data-compare="mealie-recipes/mealie"]').click();await page.locator('.resource-card [data-compare="tombursch/kitchenowl"]').click();await page.locator('#compare-dock a').click();await page.locator('.comparison-table').waitFor();assert.equal(await page.locator('.comparison-table thead th').count(),3);await noOverflow();await page.reload();await page.locator('.comparison-table').waitFor();assert.equal(await page.locator('#compare-dock [data-compare]').count(),2);await page.screenshot({path:path.join(qa,'compare-desktop.png')});
 await page.goto(base+'/#collections?topic=0');await page.locator('.topic-resource').first().waitFor();assert.equal(await page.locator('.topic-resource').count(),5);assert.equal(await page.locator('.topic-video').count(),2);await page.locator('[data-topic-anchor="topic-step-2"]').click();assert.ok(page.url().endsWith('#collections?topic=0'));await page.evaluate(()=>scrollTo(0,0));await noOverflow();await page.screenshot({path:path.join(qa,'topic-desktop.png')});
 await page.locator('.topic-video').first().click();await page.locator('.chapter-list').waitFor();assert.equal(await page.locator('#modal-content a[href="#collections?topic=0"]').count(),1);await page.locator('#close-modal').click();
 await page.locator('.topic-resource [data-detail="mealie-recipes/mealie"]').click();await page.locator('.detail-related').waitFor();assert.ok(await page.locator('.related-row').count()>0);await page.locator('.detail-experiences [data-experience]').click();const form=page.locator('#post-form');assert.equal(await form.locator('[name=kind]').inputValue(),'使用体验');await form.locator('[name=author]').fill('自动验证');await form.locator('[name=title]').fill('采购清单实际使用测试');await form.locator('[name=body]').fill('隔离数据库中的界面验证内容。');await form.locator('[type=submit]').click();await page.locator('.post-full').waitFor();
 const reply=page.locator('#reply-form');await reply.locator('[name=author]').fill('自动验证');await reply.locator('[name=body]').fill('隔离数据库中的回复。');await reply.locator('[type=submit]').click();await page.locator('.reply-block').waitFor();await page.locator('.reply-block [data-delete]').click();await page.waitForFunction(()=>document.querySelectorAll('.reply-block').length===0);
 await page.goto(base+'/#community?project=mealie-recipes%2Fmealie');await page.locator('.post-row').waitFor();assert.equal(await page.locator('#post-project').inputValue(),'mealie-recipes/mealie');await page.locator('#post-search').fill('没有这样的词');assert.equal(await page.locator('.post-row').count(),0);await page.locator('#post-search').fill('采购');assert.equal(await page.locator('.post-row').count(),1);await page.locator('.project-context [data-detail]').click();assert.equal(await page.locator('.experience-link').count(),1);await page.locator('#close-modal').click();await page.locator('.post-row [data-delete]').click();await page.waitForFunction(()=>document.querySelectorAll('.post-row').length===0);
 await page.waitForFunction(()=>!document.querySelector('#toast').classList.contains('show'));await page.setViewportSize({width:390,height:844});await page.goto(base+'/#compare');await page.locator('.comparison-table').waitFor();await noOverflow();assert.ok(await page.locator('.comparison-scroll').evaluate(e=>e.scrollWidth>e.clientWidth));await page.screenshot({path:path.join(qa,'compare-mobile.png')});
 await page.goto(base+'/#collections?topic=0');await page.locator('.topic-resource').first().waitFor();await noOverflow();await page.screenshot({path:path.join(qa,'topic-mobile.png')});await page.locator('.topic-resource [data-detail="mealie-recipes/mealie"]').click();await page.locator('.detail-related').waitFor();await noOverflow();await page.screenshot({path:path.join(qa,'detail-mobile.png')});
 await page.locator('#close-modal').click();await page.locator('#compare-clear').click();await page.setViewportSize({width:375,height:812});await page.goto(base+'/#directory');await page.locator('.resource-card').first().waitFor();await noOverflow();await page.screenshot({path:path.join(qa,'home-mobile.png')});await page.locator('#library-title').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(qa,'resources-mobile.png')});assert.deepEqual(errors,[]);
 console.log('Browser checks passed: desktop/mobile layouts, license facets, comparison persistence, topic paths, linked experience/reply/filter/delete flow; no JavaScript errors.');
})().catch(err=>{console.error(err);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.kill('SIGTERM');fs.rmSync(temp,{recursive:true,force:true});});
